name: Deploy
# 监听 push 操做   master 分支
on:
  push:
    branches:
    - master

jobs:
  build:
    stage: build
    script:
    - echo "开始构建"
#       env:
#         CI: true
# - name: Deploy to Server
#   uses: easingthemes/ssh-deploy@v2.0.7
#   env:
#     # 本地.ssh文件下的私钥id_rsa，存在secrets的TOKEN中
#     SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
#     # 复制操作的参数。"-avzr --delete"意味部署时清空服务器目标目录下的文件
#     ARGS: "-avzr --delete"
#     # 源目录，相对于$GITHUB_WORKSPACE根目录的路径
#     SOURCE: "dist/*"
#     # 服务器域名
#     REMOTE_HOST: ${{ secrets.SERVER_HOST }}
#     # 腾讯云默认用户名为root
#     REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
#     # 目标目录
#     TARGET: "/www/wwwroot/website"
